# Generated by Django 4.2.2 on 2023-07-20 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=15)),
                ("title", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=1000000000023)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to=post.models.get_upload_path
                    ),
                ),
                ("author_name", models.CharField(max_length=15)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
