# Generated by Django 4.2.2 on 2023-06-26 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=15)),
                ("title", models.CharField(max_length=255)),
                ("content", models.CharField(max_length=1023)),
                ("image", models.ImageField(upload_to="")),
                ("author_name", models.CharField(max_length=15)),
            ],
        ),
    ]
