# Generated by Django 4.2.2 on 2023-07-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogger", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
