# Generated by Django 4.2.2 on 2023-06-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogger", "0002_alter_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
