# Generated by Django 4.2.2 on 2023-06-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogger", "0003_user_country_user_gender_user_location_user_mobile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                height_field="50", null=True, upload_to="", width_field="50"
            ),
        ),
    ]
