# Generated by Django 4.2.2 on 2023-07-03 13:55

import blogger.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogger", "0005_alter_user_country_alter_user_gender_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", blogger.models.CustomUserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=150),
        ),
    ]
