# Generated by Django 4.2.2 on 2023-07-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogger", "0006_alter_user_managers_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, default="", max_length=150, null=True),
        ),
    ]
