# Generated by Django 4.2.2 on 2023-07-17 08:48

import blogger.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogger", "0007_alter_user_profile_pic_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=blogger.models.get_upload_path
            ),
        ),
    ]
